### ISSUE TITLE
Issue clonning repository.

### ISSUE THREAD

**Issue by DhimanAirao** [Tina-Linux/tina-V83x#5]
I was not able to clone the repository as guided in Readme file. It fails with error 
`fatal: remote error: upload-pack: not our ref 55a78154873a6aa4b4d28c0dbe18d649dce99f22
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'lichee/brandy-2.0/u-boot-2018', but it did not contain 55a78154873a6aa4b4d28c0dbe18d649dce99f22. Direct fetching of that commit failed.`

**To Reproduce**
Run `git clone --recursive https://github.com/Tina-Linux/tina-V83x`.

**Expected behavior**
Successful clone of repository.

**Screenshots**
![Screenshot from 2022-04-16 18-08-13](https://user-images.githubusercontent.com/39194002/163675286-2ecb0db4-500e-4d01-b5f9-bed4a0ad0f77.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04
 - Browser Firefox

**Additional context**
How to solve the issue in cloning repository?

**Comment by YuzukiTsuru** [comment]
I also found this problem here because I updated uboot locally but did not push to the remote.

I'll fix it soon.

**Comment by DhimanAirao** [comment]
Ok thank you for your reply. How long will it take to push the update as I am in hurry to build image?

**Comment by YuzukiTsuru** [comment]
Fix.

**Comment by YuzukiTsuru** [comment]
Use `git submodule update` to checkout this commit

**Comment by DhimanAirao** [comment]
Hi, Thank you for your help. Now I am able clone the repo in my host computer. But as I am from India, I am not able to download `dl files` from baidu. It will be very helpful if you can share me a files by some other means like Google Drive, weiyun etc. which can be accessed from India.

**Comment by YuzukiTsuru** [comment]
Okay, I'll upload it soon

**Comment by DhimanAirao** [comment]
Thank you. Please share me a link when you do it.

**Comment by YuzukiTsuru** [comment]
> 

https://drive.google.com/drive/folders/1PzVQIhMdAj6FnqjhwyWq9vbwgjbGUWSj?usp=sharing

**Comment by DhimanAirao** [comment]
Thank you. I am able to finally download the files. I will try to build the image now.

**Comment by DhimanAirao** [comment]
Hi, I tried to build the image but it got failed. I have attached the log file below. Any help will be beneficial.
[Buildlog.txt](https://github.com/Tina-Linux/tina-V83x/files/8507006/Buildlog.txt)
